### ISSUE TITLE
超出256个数据包后无法再继续发送

### ISSUE THREAD

**Issue by diffeet** [ZdrzalikPrzemyslaw/Xmodem-Protocol#1]
if incoming_msg == ACK:
            print("received input ACK")
            index += 1
            packet_nr += 1
            if packet_nr == 256:
                packet_nr = 1#这里应该为packet_nr = 0      只有第一个包序号为1，其他序号为0不然会传输中断

**Comment by ZdrzalikPrzemyslaw** [comment]
Yes
