### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN

### ISSUE THREAD

**Issue by Krishna27101991** [ZdrzalikPrzemyslaw/Xmodem-Protocol#2]
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats how to clear this error?

**Comment by ZdrzalikPrzemyslaw** [comment]
This project is no longer being worked on. It was created back when python 3.7 was current. Your issue probably comes from using a newer version. 

Btw, next time a quick google search will help you 🤠
